[package]
name = "rusti"
description = "a tiny image web service"
authors = ["ilotterytea <me@ilotterytea.kz>"]
version = "1.2.0"
edition = "2024"

[dependencies]
actix-multipart = "0.7.2"
actix-web = "4.10.2"
serde = { version = "1.0.219", features = ["derive"] }
